assets:
  settings.xml: yegor256/home#assets/takes/settings.xml
  pubring.gpg: yegor256/home#assets/pubring.gpg
  secring.gpg: yegor256/home#assets/secring.gpg
  s3cfg: yegor256/home#assets/s3cfg
env:
  MAVEN_OPTS: -XX:MaxPermSize=256m -Xmx1g
  JAVA_OPTS: -XX:MaxPermSize=256m -Xmx1g
install: |
  sudo locale-gen en_US en_US.UTF-8
  sudo dpkg-reconfigure locales
  export LC_ALL=en_US.UTF-8
  export LANG=en_US.UTF-8
  export LANGUAGE=en_US.UTF-8
  sudo gem install pdd
architect:
- yegor256
- davvd
merge:
  script: |
    mvn clean install -Ptakes -Pqulice --errors --settings ../settings.xml
    mvn clean site -Psite --errors --settings ../settings.xml
    mvn clean
    pdd --source=$(pwd) --verbose --file=/dev/null
  commanders:
  - alevohin
  - carlosmiranda
  - darkled
  - ggajos
  - krzyk
  - longtimeago
  - pinaf
  - yegor256
deploy:
  script: |
    mvn clean deploy -Pqulice --errors --settings ../settings.xml
    mvn clean
    pdd --source=$(pwd) --verbose --file=takes.xml
    s3cmd --no-progress put takes.xml --config=../s3cfg s3://pdd.teamed.io/takes.xml
  commanders:
  - yegor256
release:
  script: |-
    mvn versions:set "-DnewVersion=${tag}"
    git commit -am "${tag}"
    mvn clean deploy -Ptakes -Psonatype --errors --settings ../settings.xml
    mvn clean site-deploy -Ptakes -Psite --errors --settings ../settings.xml
  commanders:
  - yegor256